---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

steps:
  - name: copy
    commands:
      - "cd /opt/website"
      - "git pull"
      - "pm2 restart website"
